# generated by datamodel-codegen:
#   filename:  project.schema.json
#   timestamp: 2026-05-07T06:22:33+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Literal

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, constr


class Kind(Enum):
    plain_text = 'plain_text'
    pre_segmented = 'pre_segmented'


class Transcript(BaseModel):
    kind: Kind
    path: str


class Preset(Enum):
    draft = 'draft'
    final = 'final'


class Output(BaseModel):
    preset: Preset


class Project(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    version: Literal[1]
    name: constr(min_length=1, max_length=200)
    created_at: AwareDatetime | None = None
    updated_at: AwareDatetime | None = None
    audio: str
    transcript: Transcript
    output: Output
    layers: list[dict[str, Any]] = Field(
        ...,
        description='Ordered top-to-bottom in render stack: SUB first, BG last. Loose stub; T2.2 fills this in with full discriminated-union schema.',
    )
    subtitles: dict[str, Any] | None = None
    watermark: dict[str, Any] | None = None
