# generated by datamodel-codegen:
#   filename:  project.schema.json
#   timestamp: 2026-05-08T12:07:58+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Literal

from pydantic import (
    AwareDatetime,
    BaseModel,
    ConfigDict,
    Field,
    RootModel,
    confloat,
    conint,
    constr,
)


class RuntimeState(Enum):
    ready = 'ready'
    unavailable = 'unavailable'
    unknown = 'unknown'


class AlignmentState(Enum):
    aligned = 'aligned'
    pending = 'pending'
    missing = 'missing'


class SidecarStatus(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    status: RuntimeState
    address: str
    version: str


class VersionedRuntimeStatus(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    status: RuntimeState
    version: str


class CudaStatus(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    status: RuntimeState
    available: bool | None
    version: str
    gpu_label: str | None


class WhisperXStatus(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    status: RuntimeState
    model: str


class RuntimeHealthResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    status: Literal['ok']
    version: str
    active_renders: conint(ge=0)
    cached_projects: conint(ge=0)
    sidecar: SidecarStatus
    python: VersionedRuntimeStatus
    ffmpeg: VersionedRuntimeStatus
    cuda: CudaStatus
    whisperx: WhisperXStatus


class RecentProject(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    path: str
    name: str
    last_opened_at: str
    voice_duration: str
    sentence_count: conint(ge=0)
    media_count: conint(ge=0)
    alignment_state: AlignmentState


class Kind(Enum):
    plain_text = 'plain_text'
    pre_segmented = 'pre_segmented'


class Transcript(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    kind: Kind
    path: str


class Preset(Enum):
    draft = 'draft'
    final = 'final'


class Output(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    preset: Preset


class Kind1(Enum):
    none = 'none'
    static = 'static'
    ken_burns = 'ken_burns'
    ken_burns_strong = 'ken_burns_strong'
    zoom_in = 'zoom_in'
    zoom_out = 'zoom_out'
    pan_left = 'pan_left'
    pan_right = 'pan_right'


class Easing(Enum):
    linear = 'linear'
    ease_in = 'ease_in'
    ease_out = 'ease_out'
    ease_in_out = 'ease_in_out'


class Motion(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    kind: Kind1
    easing: Easing


class In(Enum):
    cut = 'cut'
    fade = 'fade'
    slide_left = 'slide_left'
    slide_right = 'slide_right'
    dip_black = 'dip_black'


class Out(Enum):
    cut = 'cut'
    fade = 'fade'
    slide_left = 'slide_left'
    slide_right = 'slide_right'
    dip_black = 'dip_black'


class Transitions(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    in_: In = Field(..., alias='in')
    out: Out


SentenceRangeItem = RootModel[conint(ge=1)]


SentenceRange = RootModel[list[SentenceRangeItem]]


class Anchor(Enum):
    sentences = 'sentences'
    time = 'time'


class VisualItemBase(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    id: constr(min_length=1)
    media_id: constr(min_length=1) = Field(..., alias='mediaId')
    anchor: Anchor | None = None
    from_: constr(pattern=r'^\d{1,2}:\d{2}:\d{2}\.\d{3}$') | None = Field(
        None, alias='from'
    )
    to: constr(pattern=r'^\d{1,2}:\d{2}:\d{2}\.\d{3}$') | None = None
    sentences: SentenceRange
    start: confloat(ge=0.0)
    end: confloat(ge=0.0)
    motion: Motion
    transitions: Transitions


class ForegroundItem(VisualItemBase):
    model_config = ConfigDict(
        populate_by_name=True,
    )


class PipPlacement(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    pos_x: confloat(ge=0.0, le=100.0) = Field(..., alias='posX')
    pos_y: confloat(ge=0.0, le=100.0) = Field(..., alias='posY')
    size: confloat(ge=10.0, le=70.0)
    radius: confloat(ge=0.0)
    opacity: confloat(ge=0.0, le=100.0)


class PipItem(VisualItemBase):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    pip: PipPlacement


class BackgroundItem(VisualItemBase):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    crossfade: confloat(ge=0.0)


class SubtitlesItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    id: constr(min_length=1)
    auto: Literal[True]
    label: str
    style: Literal['default']


class SubtitlesLayer(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    id: constr(min_length=1)
    kind: Literal['sub']
    name: str
    items: list[SubtitlesItem]


class ForegroundLayer(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    id: constr(min_length=1)
    kind: Literal['fg']
    name: str
    items: list[ForegroundItem]


class PipLayer(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    id: constr(min_length=1)
    kind: Literal['pip']
    name: str
    items: list[PipItem]


class BackgroundLayer(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    id: constr(min_length=1)
    kind: Literal['bg']
    name: str
    items: list[BackgroundItem]


class Position(Enum):
    bottom_center = 'bottom-center'
    top_center = 'top-center'


class BgStyle(Enum):
    none = 'none'
    shadow = 'shadow'
    box = 'box'


class SubtitleStyle(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    font: str
    size: confloat(ge=1.0)
    position: Position
    max_chars_per_line: conint(ge=1)
    bg_style: BgStyle


class SubtitlesSettings(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    burn_in: bool
    style: SubtitleStyle


class Watermark(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    media_id: constr(min_length=1) = Field(..., alias='mediaId')
    pos_x: confloat(ge=0.0, le=100.0) = Field(..., alias='posX')
    pos_y: confloat(ge=0.0, le=100.0) = Field(..., alias='posY')
    scale: confloat(ge=0.0)
    opacity: confloat(ge=0.0, le=100.0)


Layers = RootModel[SubtitlesLayer | ForegroundLayer | PipLayer | BackgroundLayer]


class Project(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    version: Literal[1]
    name: constr(min_length=1, max_length=200)
    created_at: AwareDatetime | None = None
    updated_at: AwareDatetime | None = None
    audio: str
    transcript: Transcript
    output: Output
    layers: list[Layers] = Field(
        ...,
        description='Ordered top-to-bottom in render stack: subtitles first, background last.',
    )
    subtitles: SubtitlesSettings | None = None
    watermark: Watermark | None = None
    ai: dict[str, Any] | None = None
    characters: list[dict[str, Any]] | None = None
