# generated by datamodel-codegen:
#   filename:  project.schema.json

from __future__ import annotations

from enum import Enum
from typing import Literal

from pydantic import (
    AwareDatetime,
    BaseModel,
    ConfigDict,
    Field,
    PositiveFloat,
    RootModel,
    confloat,
    conint,
    constr,
)


class RuntimeState(Enum):
    ready = 'ready'
    unavailable = 'unavailable'
    unknown = 'unknown'


class AlignmentState(Enum):
    aligned = 'aligned'
    pending = 'pending'
    missing = 'missing'


class SetupAlignmentState(Enum):
    pending = 'pending'
    running = 'running'
    aligned = 'aligned'
    failed = 'failed'


class DetectedVoiceState(Enum):
    copied = 'copied'
    copying = 'copying'
    invalid = 'invalid'


class DetectedTranscriptState(Enum):
    parsed = 'parsed'
    empty = 'empty'
    invalid = 'invalid'


class ProjectStatus(Enum):
    ready = 'ready'
    missing = 'missing'
    corrupt = 'corrupt'
    alignment_pending = 'alignment_pending'
    alignment_failed = 'alignment_failed'
    rendering = 'rendering'


class RenderStatus(Enum):
    queued = 'queued'
    running = 'running'
    done = 'done'
    error = 'error'
    cancelled = 'cancelled'
    partial = 'partial'


class RenderPreset(Enum):
    draft = 'draft'
    final = 'final'


class RenderArtifactKind(Enum):
    final_mp4 = 'final_mp4'
    draft_mp4 = 'draft_mp4'
    partial = 'partial'
    log = 'log'
    filtergraph = 'filtergraph'
    subtitles = 'subtitles'
    thumbnail = 'thumbnail'
    companion = 'companion'


class MediaKind(Enum):
    image = 'image'
    video = 'video'
    audio = 'audio'
    watermark_image = 'watermark_image'
    watermark_video = 'watermark_video'


class MediaImportMode(Enum):
    copy = 'copy'
    link = 'link'
    generated = 'generated'


class VisualCacheStatus(Enum):
    warm = 'warm'
    partial = 'partial'
    cold = 'cold'
    invalid = 'invalid'
    orphaned = 'orphaned'


class Dimensions(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    width: conint(ge=1)
    height: conint(ge=1)


class MediaAsset(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    id: constr(min_length=1)
    name: constr(min_length=1)
    kind: MediaKind
    path: constr(min_length=1)
    thumb_path: str | None = None
    dimensions: Dimensions | None = None
    duration: confloat(ge=0.0) | None = None
    size: conint(ge=0) | None = None
    hash: str | None = None
    import_mode: MediaImportMode
    imported_at: AwareDatetime


class SidecarStatus(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    status: RuntimeState
    address: str
    version: str


class VersionedRuntimeStatus(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    status: RuntimeState
    version: str


class CudaStatus(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    status: RuntimeState
    available: bool | None
    version: str
    gpu_label: str | None


class WhisperXStatus(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    status: RuntimeState
    model: str


class RuntimeHealthResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    status: Literal['ok']
    version: str
    active_renders: conint(ge=0)
    cached_projects: conint(ge=0)
    sidecar: SidecarStatus
    node: VersionedRuntimeStatus
    python: VersionedRuntimeStatus
    ffmpeg: VersionedRuntimeStatus
    cuda: CudaStatus
    whisperx: WhisperXStatus


class RecentProject(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    path: str
    name: str
    last_render_at: str
    voice_duration: str
    sentence_count: conint(ge=0)
    media_count: conint(ge=0)
    alignment_state: AlignmentState
    palette_seed: str


class RecentProjectCard(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    project_id: constr(min_length=1)
    name: constr(min_length=1)
    last_render_at: str
    voice_duration: str
    sentence_count: conint(ge=0)
    media_count: conint(ge=0)
    alignment_state: AlignmentState
    status: ProjectStatus
    thumbnail_path: str | None = None
    current_config_hash: str | None = None
    last_rendered_config_hash: str | None = None
    has_unrendered_changes: bool
    latest_render_id: str | None = None
    latest_render_status: RenderStatus | None = None


class DetectedVoice(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    path: str
    duration: confloat(ge=0.0)
    sample_rate: conint(ge=0)
    channels: conint(ge=0)
    codec: str
    state: DetectedVoiceState


class DetectedTranscript(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    path: str
    sentence_count: conint(ge=0)
    state: DetectedTranscriptState


class SetupAlignment(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    status: SetupAlignmentState
    hash: str
    device: str
    model: str
    audio_duration: confloat(ge=0.0)
    cache_hit: bool
    error: str | None = None


class DetectedInputs(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    path: str
    name: str
    voice: DetectedVoice | None
    transcript: DetectedTranscript | None
    alignment: SetupAlignment


class SetupDraft(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    project_id: constr(min_length=1) | None = None
    path: str
    name: str
    output_preset: str
    voice: DetectedVoice | None
    transcript: DetectedTranscript | None
    alignment: SetupAlignment


class AlignmentStateResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    project_id: constr(min_length=1)
    status: SetupAlignmentState
    cache_hit: bool
    hash: str | None = None
    error: str | None = None


class Kind(Enum):
    plain_text = 'plain_text'
    pre_segmented = 'pre_segmented'


class Transcript(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    kind: Kind
    path: str


class Preset(Enum):
    draft = 'draft'
    final = 'final'


class Output(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    preset: Preset
    resolution: constr(pattern=r'^\d+x\d+$') | None = None
    width: conint(ge=1) | None = None
    height: conint(ge=1) | None = None
    fps: PositiveFloat | None = None
    video_codec: constr(min_length=1) | None = None
    video_crf: int | None = None
    video_preset: str | None = None
    audio_codec: constr(min_length=1) | None = None
    audio_bitrate_kbps: conint(ge=1) | None = None
    audio_sample_rate: conint(ge=1) | None = None
    pixel_format: str | None = None
    color_space: str | None = None


class Kind1(Enum):
    none = 'none'
    static = 'static'
    ken_burns = 'ken_burns'
    ken_burns_strong = 'ken_burns_strong'
    zoom_in = 'zoom_in'
    zoom_out = 'zoom_out'
    pan_left = 'pan_left'
    pan_right = 'pan_right'


class Easing(Enum):
    linear = 'linear'
    ease_in = 'ease_in'
    ease_out = 'ease_out'
    ease_in_out = 'ease_in_out'


class Motion(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    kind: Kind1
    easing: Easing


class In(Enum):
    cut = 'cut'
    fade = 'fade'
    slide_left = 'slide_left'
    slide_right = 'slide_right'
    dip_black = 'dip_black'


class Out(Enum):
    cut = 'cut'
    fade = 'fade'
    slide_left = 'slide_left'
    slide_right = 'slide_right'
    dip_black = 'dip_black'


class Transitions(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    in_: In = Field(..., alias='in')
    out: Out


SentenceRangeItem = RootModel[conint(ge=1)]


SentenceRange = RootModel[list[SentenceRangeItem]]


class Anchor(Enum):
    sentences = 'sentences'
    time = 'time'


class VisualItemBase(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    id: constr(min_length=1)
    media_id: constr(min_length=1) = Field(..., alias='mediaId')
    media_ids: list[str] | None = Field(None, alias='mediaIds', min_length=1)
    anchor: Anchor | None = None
    from_: constr(pattern=r'^\d{1,2}:\d{2}:\d{2}\.\d{3}$') | None = Field(
        None, alias='from'
    )
    to: constr(pattern=r'^\d{1,2}:\d{2}:\d{2}\.\d{3}$') | None = None
    sentences: SentenceRange
    start: confloat(ge=0.0)
    end: confloat(ge=0.0)
    motion: Motion
    transitions: Transitions
    cache_status: VisualCacheStatus | None = None
    orphaned: bool | None = None
    orphan_reason: str | None = None


class ForegroundItem(VisualItemBase):
    model_config = ConfigDict(
        populate_by_name=True,
    )


class PipPlacement(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    pos_x: confloat(ge=0.0, le=100.0) = Field(..., alias='posX')
    pos_y: confloat(ge=0.0, le=100.0) = Field(..., alias='posY')
    size: confloat(ge=10.0, le=70.0)
    radius: confloat(ge=0.0)
    opacity: confloat(ge=0.0, le=100.0)


class PipItem(VisualItemBase):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    pip: PipPlacement


class BackgroundItem(VisualItemBase):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    crossfade: confloat(ge=0.0)


class SubtitlesItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    id: constr(min_length=1)
    auto: Literal[True]
    label: str
    style: Literal['default']


class SubtitlesLayer(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    id: constr(min_length=1)
    kind: Literal['sub']
    name: str
    items: list[SubtitlesItem]


class ForegroundLayer(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    id: constr(min_length=1)
    kind: Literal['fg']
    name: str
    items: list[ForegroundItem]


class PipLayer(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    id: constr(min_length=1)
    kind: Literal['pip']
    name: str
    items: list[PipItem]


class BackgroundLayer(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    id: constr(min_length=1)
    kind: Literal['bg']
    name: str
    items: list[BackgroundItem]


class Position(Enum):
    bottom_center = 'bottom-center'
    top_center = 'top-center'


class BgStyle(Enum):
    none = 'none'
    shadow = 'shadow'
    box = 'box'


class SubtitleStyle(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    font: str
    size: confloat(ge=1.0)
    position: Position
    max_chars_per_line: conint(ge=1)
    bg_style: BgStyle


class SubtitlesSettings(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    burn_in: bool
    style: SubtitleStyle


class Watermark(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    media_id: constr(min_length=1) = Field(..., alias='mediaId')
    pos_x: confloat(ge=0.0, le=100.0) = Field(..., alias='posX')
    pos_y: confloat(ge=0.0, le=100.0) = Field(..., alias='posY')
    scale: confloat(ge=0.0)
    opacity: confloat(ge=0.0, le=100.0)


class RenderArtifact(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    artifact_id: constr(min_length=1)
    render_id: constr(min_length=1)
    project_id: constr(min_length=1)
    kind: RenderArtifactKind
    path: constr(min_length=1)
    size: conint(ge=0) | None = None
    hash: str | None = None
    created_at: AwareDatetime
    playable: bool
    reusable: bool


class RenderHistoryRow(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    render_id: constr(min_length=1)
    project_id: constr(min_length=1)
    preset: RenderPreset
    status: RenderStatus
    filename: str | None = None
    resolution: str | None = None
    duration: confloat(ge=0.0) | None = None
    file_size: conint(ge=0) | None = None
    config_hash: str | None = None
    created_at: AwareDatetime
    completed_at: AwareDatetime | None = None
    artifacts: list[RenderArtifact]


class ProjectConfigSaveResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    project_id: constr(min_length=1)
    config_hash: constr(min_length=1)
    saved_at: AwareDatetime
    has_unrendered_changes: bool


Layers = RootModel[SubtitlesLayer | ForegroundLayer | PipLayer | BackgroundLayer]


class Project(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    version: Literal[1]
    name: constr(min_length=1, max_length=200)
    created_at: AwareDatetime | None = None
    updated_at: AwareDatetime | None = None
    project_id: constr(min_length=1) | None = None
    config_hash: constr(min_length=1) | None = None
    last_rendered_config_hash: constr(min_length=1) | None = None
    audio: str
    transcript: Transcript
    output: Output
    media: list[MediaAsset] | None = None
    layers: list[Layers] = Field(
        ...,
        description='Ordered top-to-bottom in render stack: subtitles first, background last.',
    )
    subtitles: SubtitlesSettings | None = None
    watermark: Watermark | None = None


class ProjectConfigLoadResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    project_id: constr(min_length=1)
    config: Project
    config_hash: constr(min_length=1)
    last_rendered_config_hash: str | None = None
    has_unrendered_changes: bool
