/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * This interface was referenced by `Project`'s JSON-Schema
 * via the `definition` "MediaKind".
 */
export type MediaKind = "image" | "video" | "audio" | "watermark_image" | "watermark_video";
/**
 * This interface was referenced by `Project`'s JSON-Schema
 * via the `definition` "MediaImportMode".
 */
export type MediaImportMode = "copy" | "link" | "generated";
/**
 * This interface was referenced by `Project`'s JSON-Schema
 * via the `definition` "ForegroundItem".
 */
export type ForegroundItem = VisualItemBase & VisualMediaRefConstraint;
/**
 * @minItems 2
 * @maxItems 2
 *
 * This interface was referenced by `Project`'s JSON-Schema
 * via the `definition` "SentenceRange".
 */
export type SentenceRange = [number, number];
/**
 * This interface was referenced by `Project`'s JSON-Schema
 * via the `definition` "VisualCacheStatus".
 */
export type VisualCacheStatus = "warm" | "partial" | "cold" | "invalid" | "orphaned";
/**
 * This interface was referenced by `Project`'s JSON-Schema
 * via the `definition` "VisualMediaRefConstraint".
 */
export type VisualMediaRefConstraint = {
  [k: string]: unknown;
};
/**
 * This interface was referenced by `Project`'s JSON-Schema
 * via the `definition` "PipItem".
 */
export type PipItem = VisualItemBase &
  VisualMediaRefConstraint & {
    pip: PipPlacement;
  };
/**
 * This interface was referenced by `Project`'s JSON-Schema
 * via the `definition` "BackgroundItem".
 */
export type BackgroundItem = VisualItemBase &
  VisualMediaRefConstraint & {
    crossfade: number;
  };
/**
 * This interface was referenced by `Project`'s JSON-Schema
 * via the `definition` "RuntimeState".
 */
export type RuntimeState = "ready" | "unavailable" | "unknown";
/**
 * This interface was referenced by `Project`'s JSON-Schema
 * via the `definition` "AlignmentState".
 */
export type AlignmentState = "aligned" | "pending" | "missing";
/**
 * This interface was referenced by `Project`'s JSON-Schema
 * via the `definition` "SetupAlignmentState".
 */
export type SetupAlignmentState = "pending" | "running" | "aligned" | "failed";
/**
 * This interface was referenced by `Project`'s JSON-Schema
 * via the `definition` "DetectedVoiceState".
 */
export type DetectedVoiceState = "copied" | "copying" | "invalid";
/**
 * This interface was referenced by `Project`'s JSON-Schema
 * via the `definition` "DetectedTranscriptState".
 */
export type DetectedTranscriptState = "parsed" | "empty" | "invalid";
/**
 * This interface was referenced by `Project`'s JSON-Schema
 * via the `definition` "ProjectStatus".
 */
export type ProjectStatus = "ready" | "missing" | "corrupt" | "alignment_pending" | "alignment_failed" | "rendering";
/**
 * This interface was referenced by `Project`'s JSON-Schema
 * via the `definition` "RenderStatus".
 */
export type RenderStatus = "queued" | "running" | "done" | "error" | "cancelled" | "partial";
/**
 * This interface was referenced by `Project`'s JSON-Schema
 * via the `definition` "LauncherRenderStatusTag".
 */
export type LauncherRenderStatusTag = "unrendered" | "queued" | "rendering" | "rendered" | "failed" | "cancelled";
/**
 * This interface was referenced by `Project`'s JSON-Schema
 * via the `definition` "RenderPreset".
 */
export type RenderPreset = "draft" | "final";
/**
 * This interface was referenced by `Project`'s JSON-Schema
 * via the `definition` "SetupOutputPreset".
 */
export type SetupOutputPreset = "draft" | "final" | "vertical";
/**
 * This interface was referenced by `Project`'s JSON-Schema
 * via the `definition` "RenderArtifactKind".
 */
export type RenderArtifactKind =
  | "final_mp4"
  | "draft_mp4"
  | "partial"
  | "log"
  | "filtergraph"
  | "subtitles"
  | "thumbnail"
  | "companion";
/**
 * This interface was referenced by `Project`'s JSON-Schema
 * via the `definition` "SetupSubtitleGenerationState".
 */
export type SetupSubtitleGenerationState = "ready" | "running" | "succeeded" | "failed";
/**
 * This interface was referenced by `Project`'s JSON-Schema
 * via the `definition` "SetupSubtitleCacheState".
 */
export type SetupSubtitleCacheState = "unknown" | "hit" | "miss";

export interface Project {
  version: 1;
  name: string;
  created_at?: string;
  updated_at?: string;
  project_id?: string;
  config_hash?: string;
  last_rendered_config_hash?: string;
  audio: string;
  transcript: Transcript;
  output: Output;
  media?: MediaAsset[];
  /**
   * Ordered top-to-bottom in render stack: subtitles first, background last.
   */
  layers: (SubtitlesLayer | ForegroundLayer | PipLayer | BackgroundLayer)[];
  subtitles?: null | SubtitlesSettings;
  watermark?: null | Watermark;
}
/**
 * This interface was referenced by `Project`'s JSON-Schema
 * via the `definition` "Transcript".
 */
export interface Transcript {
  kind: "plain_text" | "pre_segmented";
  path: string;
}
/**
 * This interface was referenced by `Project`'s JSON-Schema
 * via the `definition` "Output".
 */
export interface Output {
  preset: "draft" | "final";
  resolution?: "1080p" | "720p" | "9:16";
  width?: number;
  height?: number;
  fps?: number;
  video_codec?: string;
  video_crf?: number | null;
  video_preset?: string | null;
  audio_codec?: string;
  audio_bitrate_kbps?: number | null;
  audio_sample_rate?: number | null;
  pixel_format?: string | null;
  color_space?: string | null;
}
/**
 * This interface was referenced by `Project`'s JSON-Schema
 * via the `definition` "MediaAsset".
 */
export interface MediaAsset {
  id: string;
  name: string;
  kind: MediaKind;
  path: string;
  thumb_path?: string | null;
  dimensions?: Dimensions | null;
  duration?: number | null;
  size?: number | null;
  hash?: string | null;
  import_mode: MediaImportMode;
  created_at?: string | null;
  imported_at: string;
}
/**
 * This interface was referenced by `Project`'s JSON-Schema
 * via the `definition` "Dimensions".
 */
export interface Dimensions {
  width: number;
  height: number;
}
/**
 * This interface was referenced by `Project`'s JSON-Schema
 * via the `definition` "SubtitlesLayer".
 */
export interface SubtitlesLayer {
  id: string;
  kind: "sub";
  name: string;
  items: SubtitlesItem[];
}
/**
 * This interface was referenced by `Project`'s JSON-Schema
 * via the `definition` "SubtitlesItem".
 */
export interface SubtitlesItem {
  id: string;
  auto: true;
  label: string;
  style: "default";
}
/**
 * This interface was referenced by `Project`'s JSON-Schema
 * via the `definition` "ForegroundLayer".
 */
export interface ForegroundLayer {
  id: string;
  kind: "fg";
  name: string;
  items: ForegroundItem[];
}
/**
 * This interface was referenced by `Project`'s JSON-Schema
 * via the `definition` "VisualItemBase".
 */
export interface VisualItemBase {
  id: string;
  mediaId?: string;
  /**
   * @minItems 1
   */
  mediaIds?: [string, ...string[]];
  anchor?: "sentences" | "time";
  from?: string;
  to?: string;
  sentences: SentenceRange;
  start: number;
  end: number;
  motion: Motion;
  transitions: Transitions;
  cache_status?: VisualCacheStatus;
  orphaned?: boolean;
  orphan_reason?: string | null;
}
/**
 * This interface was referenced by `Project`'s JSON-Schema
 * via the `definition` "Motion".
 */
export interface Motion {
  kind: "none" | "static" | "ken_burns" | "ken_burns_strong" | "zoom_in" | "zoom_out" | "pan_left" | "pan_right";
  easing: "linear" | "ease_in" | "ease_out" | "ease_in_out";
}
/**
 * This interface was referenced by `Project`'s JSON-Schema
 * via the `definition` "Transitions".
 */
export interface Transitions {
  in: "cut" | "fade" | "slide_left" | "slide_right" | "dip_black";
  out: "cut" | "fade" | "slide_left" | "slide_right" | "dip_black";
}
/**
 * This interface was referenced by `Project`'s JSON-Schema
 * via the `definition` "PipLayer".
 */
export interface PipLayer {
  id: string;
  kind: "pip";
  name: string;
  items: PipItem[];
}
/**
 * This interface was referenced by `Project`'s JSON-Schema
 * via the `definition` "PipPlacement".
 */
export interface PipPlacement {
  posX: number;
  posY: number;
  size: number;
  radius: number;
  opacity: number;
}
/**
 * This interface was referenced by `Project`'s JSON-Schema
 * via the `definition` "BackgroundLayer".
 */
export interface BackgroundLayer {
  id: string;
  kind: "bg";
  name: string;
  items: BackgroundItem[];
}
/**
 * This interface was referenced by `Project`'s JSON-Schema
 * via the `definition` "SubtitlesSettings".
 */
export interface SubtitlesSettings {
  burn_in: boolean;
  style: SubtitleStyle;
}
/**
 * This interface was referenced by `Project`'s JSON-Schema
 * via the `definition` "SubtitleStyle".
 */
export interface SubtitleStyle {
  font: string;
  size: number;
  position: "bottom" | "bottom_low" | "top";
  max_chars_per_line: number;
  bg_style: "none" | "pill" | "block" | "shadow";
}
/**
 * This interface was referenced by `Project`'s JSON-Schema
 * via the `definition` "Watermark".
 */
export interface Watermark {
  mediaId: string;
  posX: number;
  posY: number;
  scale: number;
  opacity: number;
}
/**
 * This interface was referenced by `Project`'s JSON-Schema
 * via the `definition` "SidecarStatus".
 */
export interface SidecarStatus {
  status: RuntimeState;
  address: string;
  version: string;
}
/**
 * This interface was referenced by `Project`'s JSON-Schema
 * via the `definition` "VersionedRuntimeStatus".
 */
export interface VersionedRuntimeStatus {
  status: RuntimeState;
  version: string;
}
/**
 * This interface was referenced by `Project`'s JSON-Schema
 * via the `definition` "CudaStatus".
 */
export interface CudaStatus {
  status: RuntimeState;
  available: boolean | null;
  version: string;
  gpu_label: string | null;
}
/**
 * This interface was referenced by `Project`'s JSON-Schema
 * via the `definition` "WhisperXStatus".
 */
export interface WhisperXStatus {
  status: RuntimeState;
  model: string;
}
/**
 * This interface was referenced by `Project`'s JSON-Schema
 * via the `definition` "RuntimeHealthResponse".
 */
export interface RuntimeHealthResponse {
  status: "ok";
  version: string;
  active_renders: number;
  cached_projects: number;
  sidecar: SidecarStatus;
  node: VersionedRuntimeStatus;
  python: VersionedRuntimeStatus;
  ffmpeg: VersionedRuntimeStatus;
  cuda: CudaStatus;
  whisperx: WhisperXStatus;
}
/**
 * This interface was referenced by `Project`'s JSON-Schema
 * via the `definition` "RecentProject".
 */
export interface RecentProject {
  path: string;
  name: string;
  last_render_at: string;
  voice_duration: string;
  sentence_count: number;
  media_count: number;
  alignment_state: AlignmentState;
  palette_seed: string;
}
/**
 * This interface was referenced by `Project`'s JSON-Schema
 * via the `definition` "RecentProjectCard".
 */
export interface RecentProjectCard {
  project_id: string;
  name: string;
  last_render_at?: string | null;
  voice_duration: string;
  sentence_count: number;
  media_count: number;
  alignment_state: AlignmentState;
  status: ProjectStatus;
  thumbnail_path?: string | null;
  current_config_hash?: string | null;
  last_rendered_config_hash?: string | null;
  has_unrendered_changes: boolean;
  latest_render_id?: string | null;
  latest_render_status?: RenderStatus | null;
  render_status_tag?: LauncherRenderStatusTag | null;
}
/**
 * This interface was referenced by `Project`'s JSON-Schema
 * via the `definition` "PaginationMeta".
 */
export interface PaginationMeta {
  page_size: number;
  page_index: number;
  total_count: number;
  total_pages: number;
}
/**
 * This interface was referenced by `Project`'s JSON-Schema
 * via the `definition` "RecentProjectsPage".
 */
export interface RecentProjectsPage {
  items: RecentProjectCard[];
  pagination: PaginationMeta;
}
/**
 * This interface was referenced by `Project`'s JSON-Schema
 * via the `definition` "DetectedVoice".
 */
export interface DetectedVoice {
  path: string;
  duration: number;
  sample_rate: number;
  channels: number;
  codec: string;
  state: DetectedVoiceState;
}
/**
 * This interface was referenced by `Project`'s JSON-Schema
 * via the `definition` "DetectedTranscript".
 */
export interface DetectedTranscript {
  path: string;
  sentence_count: number;
  state: DetectedTranscriptState;
}
/**
 * This interface was referenced by `Project`'s JSON-Schema
 * via the `definition` "SetupAlignment".
 */
export interface SetupAlignment {
  status: SetupAlignmentState;
  hash: string;
  device: string;
  model: string;
  audio_duration: number;
  cache_hit: boolean;
  error?: string;
}
/**
 * This interface was referenced by `Project`'s JSON-Schema
 * via the `definition` "SetupSubtitleGenerationResult".
 */
export interface SetupSubtitleGenerationResult {
  status: SetupSubtitleGenerationState;
  cue_count: number;
  total_duration_s: number;
  cache_state: SetupSubtitleCacheState;
  error_message?: string | null;
}
/**
 * This interface was referenced by `Project`'s JSON-Schema
 * via the `definition` "DetectedInputs".
 */
export interface DetectedInputs {
  path: string;
  name: string;
  voice: null | DetectedVoice;
  transcript: null | DetectedTranscript;
  alignment: SetupAlignment;
}
/**
 * This interface was referenced by `Project`'s JSON-Schema
 * via the `definition` "SetupDraft".
 */
export interface SetupDraft {
  project_id?: string;
  path: string;
  name: string;
  output_preset: SetupOutputPreset;
  voice: null | DetectedVoice;
  transcript: null | DetectedTranscript;
  subtitle_generation: SetupSubtitleGenerationResult;
  alignment: SetupAlignment;
}
/**
 * This interface was referenced by `Project`'s JSON-Schema
 * via the `definition` "AlignmentStateResponse".
 */
export interface AlignmentStateResponse {
  project_id: string;
  status: SetupAlignmentState;
  cache_hit: boolean;
  hash?: string | null;
  error?: string | null;
}
/**
 * This interface was referenced by `Project`'s JSON-Schema
 * via the `definition` "RenderArtifact".
 */
export interface RenderArtifact {
  artifact_id: string;
  render_id: string;
  project_id: string;
  kind: RenderArtifactKind;
  path: string;
  size?: number | null;
  hash?: string | null;
  created_at: string;
  playable: boolean;
  reusable: boolean;
}
/**
 * This interface was referenced by `Project`'s JSON-Schema
 * via the `definition` "RenderHistoryRow".
 */
export interface RenderHistoryRow {
  render_id: string;
  project_id: string;
  preset: RenderPreset;
  status: RenderStatus;
  filename?: string | null;
  resolution?: string | null;
  duration?: number | null;
  file_size?: number | null;
  config_hash?: string | null;
  created_at: string;
  completed_at?: string | null;
  artifacts: RenderArtifact[];
}
/**
 * This interface was referenced by `Project`'s JSON-Schema
 * via the `definition` "ProjectConfigLoadResponse".
 */
export interface ProjectConfigLoadResponse {
  project_id: string;
  config: Project;
  config_hash: string;
  last_rendered_config_hash?: string | null;
  has_unrendered_changes: boolean;
}
/**
 * This interface was referenced by `Project`'s JSON-Schema
 * via the `definition` "ProjectConfigSaveResponse".
 */
export interface ProjectConfigSaveResponse {
  project_id: string;
  config_hash: string;
  saved_at: string;
  has_unrendered_changes: boolean;
}
