/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Project {
  version: 1;
  name: string;
  created_at?: string;
  updated_at?: string;
  audio: string;
  transcript: {
    kind: "plain_text" | "pre_segmented";
    path: string;
    [k: string]: unknown;
  };
  output: {
    preset: "draft" | "final";
    [k: string]: unknown;
  };
  /**
   * Ordered top-to-bottom in render stack: SUB first, BG last. Loose stub; T2.2 fills this in with full discriminated-union schema.
   */
  layers: {
    [k: string]: unknown;
  }[];
  subtitles?: {
    [k: string]: unknown;
  } | null;
  watermark?: {
    [k: string]: unknown;
  } | null;
}
